[["@"]]
type = "MX"
values = ["mx01.mail.icloud.com.", "mx02.mail.icloud.com."]

[["@"]]
type = "TXT"
	[["@".values]]
	exchange = "mx01.mail.icloud.com."
	preference = 10

	[["@".values]]
	exchange = "mx02.mail.icloud.com."
	preference = 20

[[sig1._domainkey]]
type = "CNAME"
value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."
