"sig1._domainkey" = {type = "CNAME", value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."}
#"sig1._domainkey" = {type = "CNAME", value = "sig1.dkim.f.cole.ws.at.icloudmailadmin.com."}

ridgeback = {type = "A", value = "152.67.248.193"}
fireball = {type = "A", value = "152.67.225.191"}
"*.ridgeback" = {type = "A", value = "152.67.248.193"}
"*.fireball" = {type = "A", value = "152.67.225.191"}
"www" = {type = "CNAME", value = "colews.netlify.app."}


[["@"]]
type = "ALIAS"
values = "apex-loadbalancer.netlify.com."

[["@"]]
type = "MX"
values = [
#	{exchange="mx1.improvmx.com.", preference = 10},
#	{exchange="mx2.improvmx.com.", preference = 20},
	{exchange="mx01.mail.icloud.com.", preference = 10},
	{exchange="mx02.mail.icloud.com.", preference = 10},
]
[["@"]]
type = "TXT"
values = ["apple-domain=lc3PH4xC5unAZ9aq", "v=spf1 redirect=icloud.com"]

[[f]]
type = "MX"
values = [
	{exchange="mx01.mail.icloud.com.", preference = 10},
	{exchange="mx02.mail.icloud.com.", preference = 10},
]

[[f]]
type = "TXT"
values = ["apple-domain=DJhWxHXKq4LG6Zzg", "v=spf1 redirect=icloud.com"]
