[["@"]]
type = "A"
values = ["52.203.36.44", "52.73.87.228"]

[["@"]]
type = "MX"
	[["@".values]]
	exchange = "mx01.mail.icloud.com."
	preference = 10
	[["@".values]]
	exchange = "mx02.mail.icloud.com."
	preference = 10

["sig1._domainkey"]
type = "CNAME"
value = "sig1.dkim.colewilson.xyz.at.icloudmailadmin.com."

[["@"]]
type = "TXT"
values = ["apple-domain=QTavCrI9LI5cSQIi", "v=spf1 redirect=icloud.com"]

[["@"]]
type = "AAAA"
values = ["2604:a880:400:d0::1738:6001", "2604:a880:400:d0::1757:9001"]

["*"]
type = "CNAME"
value = "colewilson.netlify.app."

[scrapbook]
type = "CNAME"
value = "cname.vercel-dns.com."
