[[@]]
type = "MX"
values = ["mx01.mail.icloud.com.", "mx02.mail.icloud.com."]

[[@]]
type = "TXT"
values = [
	"apple-domain=bmH8TRC119hU46V3",
	"v=spf1 redirect=icloud.com"
]

[[sig1._domainkey]]
type = "CNAME"
value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."
