

bin = {type = "A", value = "152.67.248.193"}
assignmentlogger = {type="CNAME", value="cole-wilson.github.io."}
gerrymander = {type="CNAME", value="cole-wilson.github.io."}

nosource = {type = "A", value = "152.67.248.193"}
historytimeline = {type="CNAME", value="cole-wilson.github.io."}
ctf = {type = "A", value = "152.67.248.193"}
http = {type = "A", value = "152.67.248.193"}
ridgeback = {type = "A", value = "152.67.248.193"}
fireball = {type = "A", value = "152.67.225.191"}
"*.ridgeback" = {type = "A", value = "152.67.248.193"}
"*.fireball" = {type = "A", value = "152.67.225.191"}
www = {type = "CNAME", value = "cole-wilson.github.io."}
desmos = {type = "CNAME", value = "cole-wilson.github.io."}
clock = {type="CNAME", value="cole-wilson.github.io."}
siddhartha = {type="CNAME", value="cole-wilson.github.io."}
reactiontime = {type="CNAME", value="cole-wilson.github.io."}
worldcup= {type="CNAME", value="cole-wilson.github.io."}
"sig1._domainkey" = {type = "CNAME", value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."}
laptop = {type = "A", value = "192.168.0.81"}
"*.laptop" = {type = "A", value = "192.168.0.81"}
"docs.google.com.document.d.qjsovaddglwxljkt5pq0jsovadglytyte0k" = {type = "A", value = "152.67.225.191"}
applesauce = {type="CNAME", value="cole-wilson.github.io."}
windows = {type="CNAME", value="cole-wilson.github.io."}
snow = {type="CNAME", value="cole-wilson.github.io."}

"_github-pages-challenge-cole-wilson" = {type="TXT", value="24ef40b288397581b9a91aac44633a"}

[["@"]]
type="ALIAS"
value="apex-loadbalancer.netlify.com."

# [["@"]] 
# type="A"
# value="75.2.60.5"

# [["@"]]
# type = "ALIAS"
# value = "cole-wilson.github.io."

[["@"]]
type = "MX"
values = [
	{exchange="mx01.mail.icloud.com.", preference = 10},
	{exchange="mx02.mail.icloud.com.", preference = 10},
]

[["@"]]
type = "TXT"
values = [
	"v=spf1 redirect=icloud.com include:icloud.com ~all",
	"apple-domain=cscpnfpJE1fvkkyl",
	"google-site-verification=wQK8ZNYSxhp5heE1UlmHUYQxpPbQ24RjqTW_p_DXI54"
]
