bin = {type = "A", value = "152.67.248.193"}
nosource = {type = "A", value = "152.67.248.193"}
ctf = {type = "A", value = "152.67.248.193"}
http = {type = "A", value = "152.67.248.193"}
ridgeback = {type = "A", value = "152.67.248.193"}
fireball = {type = "A", value = "152.67.225.191"}
"*.ridgeback" = {type = "A", value = "152.67.248.193"}
"*.fireball" = {type = "A", value = "152.67.225.191"}
www = {type = "CNAME", value = "colews.netlify.app."}
"sig1._domainkey" = {type = "CNAME", value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."}


[["@"]]
type = "ALIAS"
value = "apex-loadbalancer.netlify.com."

[["@"]]
type = "MX"
values = [
	{exchange="mx01.mail.icloud.com.", preference = 10},
	{exchange="mx02.mail.icloud.com.", preference = 10},
]

[["@"]]
type = "TXT"
values = [
	"v=spf1 redirect=icloud.com include:icloud.com ~all",
	"apple-domain=cscpnfpJE1fvkkyl",
	"google-site-verification=wQK8ZNYSxhp5heE1UlmHUYQxpPbQ24RjqTW_p_DXI54"
]
