[["@"]]
type = "MX"
values = [
	{exchange="mx1.improvmx.com.", preference = 10},
	{exchange="mx2.improvmx.com.", preference = 20},
	{exchange="mx01.mail.icloud.com.", preference = 110},
	{exchange="mx02.mail.icloud.com.", preference = 120},
]

[["@"]]
type = "TXT"
values = ["apple-domain=bmH8TRC119hU46V3", "v=spf1 redirect=icloud.com"]

[["sig1._domainkey"]]
type = "CNAME"
value = "sig1.dkim.cole.ws.at.icloudmailadmin.com."

[ridgeback]
type = "A"
value = "152.67.248.193"
["*.ridgeback"]
type = "A"
value = "152.67.248.193"

[fireball]
type = "A"
value = "152.67.225.191"
[["*.fireball"]]
type = "A"
value = "152.67.225.191"
