[["@"]]
type = "MX"
	[["@".values]]
	exchange = "mx1.improvmx.com."
	preference = 10
	[["@".values]]
	exchange = "mx2.improvmx.com."
	preference = 20
	[["@".values]]
	exchange = "mx01.mail.icloud.com."
	preference = 10
	[["@".values]]
	exchange = "mx02.mail.icloud.com."
	preference = 10

[["@"]]
type = "TXT"
values = ["apple-domain=QTavCrI9LI5cSQIi", "v=spf1 redirect=icloud.com"]

[["sig1._domainkey"]]
type = "CNAME"
value = "sig1.dkim.colewilson.xyz.at.icloudmailadmin.com."
