[["@"]]
type = "MX"
values = [
	{exchange="mx1.improvmx.com.", preference = 10},
	{exchange="mx2.improvmx.com.", preference = 20},
	{exchange="mx01.mail.icloud.com.", preference = 110},
	{exchange="mx02.mail.icloud.com.", preference = 120},
]

[["@"]]
type = "TXT"
values = ["apple-domain=QTavCrI9LI5cSQIi", "v=spf1 redirect=icloud.com"]

[["@"]]
type = "ALIAS"
value = "apex-loadbalancer.netlify.com."

# [["@"]]
# type = "A"
# value = "75.2.60.5"




[["sig1._domainkey"]]
type = "CNAME"
value = "sig1.dkim.colewilson.xyz.at.icloudmailadmin.com."
