# main site
"www" = {type = "CNAME", value = "hogwarts-email.netlify.app."}

[["@"]]
type = "ALIAS"
value = "apex-loadbalancer.netlify.com."

# email
[["@"]]
type = "MX"
values = [
	{exchange="mx1.improvmx.com.", preference = 10},
	{exchange="mx2.improvmx.com.", preference = 20}
]

[["@"]]
type = "TXT"
values = ["v=spf1 include:spf.improvmx.com ~all",]
