          __________-------____                 ____-------__________
          \------____-------___--__---------__--___-------____------/
           \//////// / / / / / \   _-------_   / \ \ \ \ \ \\\\\\\\/
             \////-/-/------/_/_| /___   ___\ |_\_\------\-\-\\\\/
               --//// / /  /  //|| (O)\ /(O) ||\\  \  \ \ \\\\--
                    ---__/  // /| \_  /V\  _/ |\ \\  \__---
                         -//  / /\_ ------- _/\ \  \\-
                           \_/_/ /\---------/\ \_\_/
                               ----\   |   /----
                                    | -|- |
                                   /   |   \
                        __________ ---- \___|_______________
                        |\ owl@hogwarts.email             /|
                        | \Roost Under the Eaves         / |
                        |  \          _.-+=+-._         /  |
                        |   \_______."         ".______/   |
                        |  /        ' HOGWARTS  '       \  |
                        | /         *_         _*        \ |
                        |/___________ '=-_._-='___________\|
