name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3'
      - name: Install OctoDNS
        run: pip install 'octodns==0.9.10' 'pyyaml' 'toml'
      - name: toml -> yaml
        run: python ./main.py
      - name: Sync w/ production DNS providers
        run: ./.github/bin/sync
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
