name: deploy

on:
  push:
    branches:
      - main

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3'
      - name: install dependencies
        run: pip install 'octodns==0.9.10' 'pyyaml' 'toml'
      - name: toml -> yaml
        run: python ./.github/bin/main.py
      - name: sync
        run: ./.github/bin/sync
        env:
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
